---
# tasks file for ubuntu-config-playbook
- name: Configure Ubuntu 20.04 for Igor Zinovik
  hosts: localhost
  vars:
    dotfiles_dir: /home/izinovik/dotfiles
    make_targets:
      - shell
      - vim
    applications:
      - acpi
      - blueman
      - curl
      - dnssec-trigger
      - docker.io
      - dropbox
      - firefox-esr
      - git
      - jq
      - keepassxc
      - kubectl
      - make
      - net-tools
      - scrot
      - spectrwm
      - ssh
      - teamviewer
      - tmux
      - unbound
      - vim
      - vlc
      - xbindkeys
      - xclip
      - xterm
      - xtrlock
      - xxkb
      - zsh
    snaps:
      - chromium
      - restic
      - skype
      - telegram-desktop
    repos:
      - "deb http://linux.dropbox.com/ubuntu xenial main"
      - "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      - "deb http://linux.teamviewer.com/deb stable main"
      - "ppa:phoerious/keepassxc"
      - "ppa:mozillateam/ppa"
    apt_keys:
      - 1C61A2656FB57B7E4DE0F4C1FC918B335044912E # Dropbox
      - 8CAE012EBFAC38B17A937CD8C5E224500C1289C0 # Teamviewer
      - 0AB215679C571D1C8325275B9BDB3D89CE49EC21 # Mozilla team PPA

  tasks:
   - include: tasks/applications.yml
     tags: [ apps ]
   - include: tasks/snaps.yml
   - include: tasks/git.yml
   - include: tasks/make.yml
...
