---
# tasks file for ubuntu-config-playbook
- name: Configure Ubuntu for Igor Zinovik
  hosts: localhost
  vars:
    dotfiles_dir: /home/izinovik/dotfiles
    make_targets:
      - shell
      - vim
    applications:
      - acpi
      - blueman
      - curl
      - dnssec-trigger
      - docker.io
      - git
      - jq
      - keepassxc
      - kubectl
      - make
      - net-tools
      - scrot
      - spectrwm
      - ssh
      - tmux
      - unbound
      - vim
      - vlc
      - xbindkeys
      - xclip
      - xterm
      - xtrlock
      - xxkb
      - zsh
    snaps:
      - chromium
      - restic
      - skype
      - telegram-desktop
      - zoom-client
    repos:
      - "deb [arch=amd64] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
      - "deb http://repo.yandex.ru/yandex-disk/deb/ stable main"
      - "ppa:phoerious/keepassxc"
    apt_keys:
      - EE2C95AB58DC2B0138D16B4FEFC4571D7C90E5AF # Yandex Disk

  tasks:
   - include: tasks/applications.yml
     tags: [ apps ]
   - include: tasks/snaps.yml
     tags: [ apps ]
   - include: tasks/git.yml
   - include: tasks/make.yml
   - include: tasks/files.yml
   - include: tasks/a2dp-bluetooth-pulseaudio.yml
...
