---
# tasks file for ubuntu-config-playbook
- name: Configure Ubuntu 24.04 for Igor Zinovik
  hosts: localhost
  become: true
  vars:
    dotfiles_dir: /home/izinovik/dotfiles
    make_targets:
      - shell
      - vim
      - x11
    applications:
      - acpi
      - blueman
      - curl
      - dnssec-trigger
      - docker.io
      - feh
      - git
      - jq
      - keepassxc
      - kubectl
      - make
      - net-tools
      - nodejs
      - npm
      - pulseaudio-utils
      - rbenv
      - rclone
      - restic
      - scrot
      - spectrwm
      - ssh
      - tmux
      - unbound
      - unbound-anchor
      - vim
      - virtualenv
      - virtualenvwrapper
      - vlc
      - xbindkeys
      - xclip
      - xterm
      - xtrlock
      - xxkb
      - zsh
    snaps:
      - chezmoi
      - chromium
      - telegram-desktop
      - zoom-client
    repos:
      - "deb [arch=amd64] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
      - "deb [arch=amd64] http://repo.yandex.ru/yandex-disk/deb/ stable main"
      - "deb [arch=amd64] https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu noble main"
    apt_keys:
      - EE2C95AB58DC2B0138D16B4FEFC4571D7C90E5AF # Yandex Disk
      - D89C66D0E31FEA2874EBD20561922AB60068FCD6 # ppa:phoerious/keepassxc
    files:
      - src: files/01x11-has_option
        dest: /etc/X11/Xsession.d/01x11-has_option
      - src: files/unbound.conf
        dest: /etc/unbound/unbound.conf

  tasks:
    - name: Install applications
      ansible.builtin.include_tasks:
        file: tasks/applications.yml
        apply:
          tags: [apps]
      tags: [apps]
    - name: Install snaps
      ansible.builtin.include_tasks:
        file: tasks/snaps.yml
        apply:
          tags: [apps]
      tags: [apps]
    - name: Clone git repository with dot files
      ansible.builtin.include_tasks: tasks/git.yml
    - name: Run make targets
      ansible.builtin.include_tasks: tasks/make.yml
    - name: Copy files
      ansible.builtin.include_tasks:
        file: tasks/files.yml
        apply:
          tags: [files]
      tags: [files]
