---
# tasks file for ubuntu-config-playbook
- name: Configure Ubuntu 24.04 for Igor Zinovik
  hosts: localhost
  vars:
    dotfiles_dir: /home/izinovik/dotfiles
    make_targets:
      - shell
      - vim
      - x11
    applications:
      - acpi
      - blueman
      - curl
      - dnssec-trigger
      - docker.io
      - feh
      - git
      - jq
      - keepassxc
      - kubectl
      - make
      - net-tools
      - pulseaudio-utils
      - rclone
      - restic
      - scrot
      - spectrwm
      - ssh
      - tmux
      - unbound
      - unbound-anchor
      - vim
      - vlc
      - xbindkeys
      - xclip
      - xterm
      - xtrlock
      - xxkb
      - zsh
    snaps:
      - chromium
      - telegram-desktop
      - zoom-client
    repos:
      - "deb [arch=amd64] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
      - "deb http://repo.yandex.ru/yandex-disk/deb/ stable main"
      - "ppa:phoerious/keepassxc"
    apt_keys:
      - EE2C95AB58DC2B0138D16B4FEFC4571D7C90E5AF # Yandex Disk
    files:
      - src: files/01x11-has_option
        dest: /etc/X11/Xsession.d/01x11-has_option
      - src: files/unbound.conf
        dest: /etc/unbound/unbound.conf

  tasks:
    - name: Install applications
      ansible.builtin.include_tasks: tasks/applications.yml
      tags: [apps]
    - name: Install snaps
      ansible.builtin.include_tasks: tasks/snaps.yml
      tags: [apps]
    - name: Clone git repository with dot files
      ansible.builtin.include_tasks: tasks/git.yml
    - name: Run make targets
      ansible.builtin.include_tasks: tasks/make.yml
    - name: Copy files
      ansible.builtin.include_tasks: tasks/files.yml
      tags: [files]
    - name: Install file for bluetooh headset
      ansible.builtin.include_tasks: tasks/a2dp-bluetooth-pulseaudio.yml
...
