---
- name: Editing /etc/pulse/default.pa (Bluetooth profile restore)
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^load-module module-card-restore'
    line: 'load-module module-card-restore restore_bluetooth_profile=true'
