---
- name: Adding GPG keys
  ansible.builtin.apt_key:
    id: "{{ item }}"
    keyserver: keyserver.ubuntu.com
    state: present
  loop: "{{ apt_keys }}"

- name: Adding repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ repos }}"

- name: Updating apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Installing packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ applications }}"
