---
- name: Adding GPG keys
  apt_key:
    id: "{{ item }}"
    keyserver: keyserver.ubuntu.com
    state: present
  loop: "{{ apt_keys }}"

- name: Adding repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ repos }}"

- name: Updating apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Installing packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ applications }}"
