---
- name: Install restic service file
  ansible.builtin.template:
    src: templates/restic-backup.service.j2
    dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/restic-backup.service"
    owner: izinovik
    mode: "0644"

- name: Install restic timer file
  ansible.builtin.template:
    src: templates/restic-backup.timer.j2
    dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/restic-backup.timer"
    owner: izinovik
    mode: "0644"

- name: Enable systemd restic-backup.timer
  become: false
  ansible.builtin.systemd_service:
    name: restic-backup.timer
    daemon_reload: true
    scope: user
    state: started
    enabled: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}"

- name: Fill ~/.restic.env file with password and configure rclone backend
  ansible.builtin.debug:
    msg: "Please do not forget to populate ~/.restic.env file, configure rclone backend for restic and prepare ~/restic-backup.list"
